name: CI

on: [push]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - "clang:13"
          - "gcc:11"
        build_type: [Debug, Release]

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foonathan/${{matrix.image}}

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Download QBE
      run: curl https://c9x.me/compile/release/qbe-1.0.tar.xz -o qbe.tar.xz && tar xf qbe.tar.xz
    - name: Build QBE
      working-directory: qbe-1.0/
      run: apt-get install -y --no-install-recommends make && make install

    - name: Configure
      working-directory: build/
      run: cmake -GNinja $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
    - name: Build
      working-directory: build/
      run: cmake --build .
    - name: Test
      working-directory: build/
      run: ctest --output-on-failure

